---
- name: download 12.4 wkhtmltopdf
  get_url:
    url=http://download.gna.org/wkhtmltopdf/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
    dest=/tmp/
    
- name: extract wkhtmtopdf
  unarchive:
    src=/tmp/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
    dest=/tmp/
    copy=no

- name: install wkhtmltopdf by copying to the proper /usr/local/ dirs
  shell:
    cp -r /tmp/wkhtmltox/* /usr/local/


- name: copy up the footer.html file
  copy:
    src=footer.html
    dest=/home/{{deploy_user}}/footer.html
    mode=0644
    owner={{deploy_user}}
    group={{deploy_user}}