---
-
  hosts: all
  remote_user: root
  vars_files:
    - vars/main.yml
  roles:
    - initial-setup

-
  hosts: all
  remote_user: "{{deploy_user}}"
  become: true
  become_method: sudo
  vars_files:
    - vars/main.yml
    - vars/gemstone.yml 
  roles:
    - gemstone
    - staticFileServer
    - nginx
 