---
# see http://toroid.org/ams/git-website-howto for more detail about why this happens

  - name: make user level asset dir
    file:
      path="/home/{{deploy_user}}/www/{{domain}}"
      owner={{deploy_user}}
      group={{deploy_user}}
      state=directory

      
  - name: initialize empty git repo
    command:
      git init --bare
      chdir="/home/{{deploy_user}}/www/{{domain}}"


  - name: chown the git repos to the deploy_user
    command:
      "chown -R {{deploy_user}}:{{www_user}} /home/{{deploy_user}}/www/{{domain}}"

    
  - name: make /var/www/site asset dir 
    file:
      path="/var/www/{{domain}}"
      owner={{deploy_user}}
      group={{www_user}}
      state=directory

      
  - name: make post-receive hook 
    template:
      src=post-receive.j2
      dest="/home/{{deploy_user}}/www/{{domain}}/hooks/post-receive"
      mode=0755

       