#!/bin/bash
export GS_HOME=/opt/git/GsDevKit_home/
source ${GS_HOME}/bin/defGsDevKit.env
stonePath=$GS_SERVER_STONES/{{stoneName}}
pushd $stonePath $stonePath >& /dev/null
source $stonePath/stone.env
popd >& /dev/null

export GEMSTONE_NRS_ALL='#dir:$GEMSTONE_DATADIR#log:/$GEMSTONE_LOGDIR/%N%P.log'

export GEMSTONE_SYS_CONF=$GEMSTONE_DATADIR/system.conf
export GEMSTONE_EXE_CONF=$GEMSTONE_DATADIR

exec setuidgid {{user}}  fghack $GEMSTONE/bin/startnetldi -g -a {{user}} -n -l $GEMSTONE_LOGDIR/gs64ldi.log -P {{net_ldi_main}} 
