#!/bin/bash
# for use by daemontools to start the seaside gems
export GS_HOME=/opt/git/GsDevKit_home/
source ${GS_HOME}/bin/defGsDevKit.env
stonePath=$GS_SERVER_STONES/{{stoneName}}
pushd $stonePath $stonePath >& /dev/null
source $stonePath/stone.env
popd >& /dev/null

$GEMSTONE/bin/waitstone $GEMSTONE_NAME 2
exec setuidgid {{user}} $GEMSTONE/seaside/bin/{{item.name}}Gem_oodb31 daemontools-{{item.name}}-{{item.port}} {{item.port}}
